version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "20:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "20:00"
      timezone: "Europe/Berlin"
    ignore:
      - dependency-name: "forge"
