modLoader = "mcdepprovider"
loaderVersion = "[1,)"
license = "Apache-2.0"
issueTrackerURL = "https://github.com/LolHens/mc-blockshifter/issues"

[[mods]]
modId = "blockshifter"
version = "${file.jarVersion}"
displayName = "Blockshifter"
displayURL = "https://github.com/LolHens/mc-blockshifter"
logoFile = "assets/blockshifter/icon.png"
authors = "LolHens"
description = "This mod lets you slide blocks on special rails."

[[mixins]]
config = "blockshifter.mixins.json"

[[dependencies.blockshifter]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockshifter]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
