plugins {
    id 'idea'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'scala'
    apply plugin: 'idea'

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(21)
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 21
    }

    tasks.withType(ScalaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    archivesBaseName = "${rootProject.archives_base_name}-${project.parent.name}-${project.name}"
    version = "${rootProject.version}+${project.parent.name}-${project.name}"
    group = rootProject.group

    repositories {
        mavenCentral()
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }
        maven {
            name = 'FabricMC'
            url = 'https://maven.fabricmc.net/'
        }
    }
}
