# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: release

on:
  release:
    types: [published]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          CI_VERSION: ${{ github.ref }}
        run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          path: '*/build/libs/*'
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: '*/build/libs/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
